#############################################################
# Node Exporter
#
# Infrastructure metrics collection
#
# Collected Metrics:
# - CPU
# - Memory
# - Disk
# - Filesystem
# - Network
#
#############################################################

resources:

  # Node Exporter DaemonSet
  - daemonset.yaml

  # Node Exporter Service
  - service.yaml
