#############################################################
# Promtail
#############################################################

resources:
  - configmap.yaml
  - daemonset.yaml
  - serviceaccount.yaml
