resources:
  - namespace.yaml
  - datasource-configmap.yaml
  - dashboard-provider-configmap.yaml

  - dashboard-configmaps/application-dashboard.yaml
  - dashboard-configmaps/kubernetes-dashboard.yaml
  - dashboard-configmaps/infrastructure-dashboard.yaml
  - dashboard-configmaps/executive-dashboard.yaml

  - deployment.yaml
  - service.yaml
