#############################################################
# Loki
#############################################################

resources:

  # Configuration
  - configmap.yaml

  # Runtime Components
  - deployment.yaml
  - service.yaml
