apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring

data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: default

    receivers:
      - name: default

    inhibit_rules:
      - source_match:
          severity: critical
        target_match:
          severity: warning
        equal:
          - alertname
