apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: techwave-servicemonitor
  namespace: techwave
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: techwave
  namespaceSelector:
    any: false
    matchNames:
      - techwave
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
