# ==========================================
# Secretos de la aplicación
# ==========================================

apiVersion: v1
kind: Secret

metadata:
  name: techwave-secret
  namespace: techwave

type: Opaque

stringData:

  API_KEY: "techwave-demo-key"
