apiVersion: v1
kind: Service
metadata:
  name: techwave-service
  namespace: techwave
  labels:
    app: techwave
spec:
  selector:
    app: techwave
    version: blue
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: http
      protocol: TCP
  type: ClusterIP
