#############################################################
# TechWave DevOps Platform
#
# File: configmap.yaml
#
# Purpose:
# Prometheus configuration.
#
# Responsibilities:
# - Scrape application metrics
# - Scrape infrastructure metrics
# - Scrape container metrics
# - Integrate with OpenTelemetry
# - Integrate with Alertmanager
#
# Monitoring Stack:
# - Prometheus
# - Grafana
# - Loki
# - Promtail
# - Alertmanager
# - OpenTelemetry Collector
# - Node Exporter
# - cAdvisor
#
#############################################################

apiVersion: v1
kind: ConfigMap

metadata:
  name: prometheus-config
  namespace: monitoring

data:

  ###########################################################
  # Main Prometheus Configuration
  ###########################################################

  prometheus.yml: |

    #########################################################
    # Global Configuration
    #########################################################

    global:

      # Default scrape interval
      scrape_interval: 15s

      # Rule evaluation interval
      evaluation_interval: 15s

    #########################################################
    # Alertmanager Integration
    #########################################################

    alerting:

      alertmanagers:

        - static_configs:

            - targets:

                - alertmanager.monitoring.svc.cluster.local:9093

    #########################################################
    # Alert Rules Files
    #########################################################

    rule_files:

      - rules.yaml

    #########################################################
    # Scrape Jobs
    #########################################################

    scrape_configs:

      #######################################################
      # Prometheus Self Monitoring
      #######################################################

